name: flutsim
description: A powerful Flutter CLI tool for enhanced development experience with auto-reload, hot reload, and instant UI updates
version: 1.0.1
homepage: https://github.com/Rikenpatell/Flutsim.git
repository: https://github.com/Rikenpatell/Flutsim.git
#issue_tracker: https://github.com/Rikenpatell/Flutsim.git/issues
#ocumentation: https://github.com/Rikenpatell/Flutsim.git#readme

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.4.2
  shelf: ^1.4.0
  shelf_static: ^1.1.2
  qr: ^3.0.1
  path: ^1.8.3
  image: ^4.5.4
  watcher: ^1.1.0
  web_socket_channel: ^2.4.0
  web: ^0.5.0
  http: ^1.1.0
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

executables:
  flutsim:

topics:
  - flutter
  - development
  - cli
  - hot-reload
  - productivity

platforms:
  windows:
  linux:
  macos:
